on: push
name: Build & Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup dotnet
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: Build
      shell: bash
      run: |
        dotnet build NStrip -c Release -f net452
        dotnet publish NStrip -c Release -f net6.0 -r linux-x64
        mkdir -p publish
        cp NStrip/bin/Release/net452/NStrip.exe publish/
        cp NStrip/bin/Release/net6.0/linux-x64/publish/NStrip publish/NStrip-linux
    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: NStrip-builds
        path: publish/
    - name: Release
      uses: softprops/action-gh-release@master
      if: startsWith(github.ref, 'refs/tags')
      with:
        draft: true
        prerelease: false
        files: |
          publish/NStrip.exe
          publish/NStrip-linux
