on: push
name: Build & Release

jobs:
  build:
    permissions:
      contents: write
      discussions: write

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    # Build and publish for all platforms
    - name: Build
      run: |
        dotnet publish NStrip -c Release -f net6.0 -r win-x64
        dotnet publish NStrip -c Release -f net6.0 -r osx-x64
        dotnet publish NStrip -c Release -f net6.0 -r linux-x64
    
    # Upload artifacts for each platform
    - name: Upload Windows
      uses: actions/upload-artifact@v4
      with:
        name: NStrip-win-x64
        path: NStrip/bin/Release/net6.0/win-x64/publish/NStrip.exe
    - name: Upload Linux
      uses: actions/upload-artifact@v4
      with:
        name: NStrip-linux-x64
        path: NStrip/bin/Release/net6.0/linux-x64/publish/NStrip
    - name: Upload macOS
      uses: actions/upload-artifact@v4
      with:
        name: NStrip-osx-x64
        path: NStrip/bin/Release/net6.0/osx-x64/publish/NStrip
    
    # Create release if a tag is pushed
    - name: Rename files
      if: startsWith(github.ref, 'refs/tags')
      run: |
        mkdir -p publish
        cp NStrip/bin/Release/net6.0/win-x64/publish/NStrip.exe publish/NStrip-win-x64.exe
        cp NStrip/bin/Release/net6.0/linux-x64/publish/NStrip publish/NStrip-linux-x64
        cp NStrip/bin/Release/net6.0/osx-x64/publish/NStrip publish/NStrip-osx-x64
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags')
      with:
        draft: true
        prerelease: false
        files: |
          publish/NStrip-win-x64.exe
          publish/NStrip-linux-x64
          publish/NStrip-osx-x64
