on: push
name: Build & Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Build
      shell: bash
      run: |
        dotnet publish NStrip -c Release -f net6.0 -r win-x64
        dotnet publish NStrip -c Release -f net6.0 -r osx-x64
        dotnet publish NStrip -c Release -f net6.0 -r linux-x64
        mkdir -p publish
        cp NStrip/bin/Release/net6.0/win-x64/publish/NStrip.exe publish/NStrip.exe
        cp NStrip/bin/Release/net6.0/osx-x64/publish/NStrip publish/NStrip-mac
        cp NStrip/bin/Release/net6.0/linux-x64/publish/NStrip publish/NStrip-linux
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: NStrip-builds
        path: publish/
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags')
      with:
        draft: true
        prerelease: false
        files: |
          publish/NStrip.exe
          publish/NStrip-linux
